name: CD Workflow

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  cd-deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      - name: Configure Databricks
        run: |
          cat <<EOF > ~/.databrickscfg
          [TEST]
          host = https://adb-7405616190047052.12.azuredatabricks.net/
          azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}
          EOF

      - name: Deploy to TEST
        run: |
          databricks bundle deploy \
            --target test \
            --profile TEST

  cd-deploy-prod:
    name: Deploy to PROD
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      - name: Configure Databricks
        run: |
          cat <<EOF > ~/.databrickscfg
          [PROD]
          host = https://adb-7405608822547512.12.azuredatabricks.net/
          azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}
          EOF

      - name: Deploy to PROD
        run: |
          databricks bundle deploy \
            --target prod \
            --profile PROD
